STRINGS = {
    "en": {
        "name": "1. English",
        "setup_title": "TROCKEY 4K SETUP",
        "select_lang": "Select Language:",
        "how_many": "How many humans? (Press 0, 1, 2, or 3)",
        "choose_side": "Player {} choose side:",
        "press_left": "Press 1 for LEFT (WASD)",
        "press_right": "Press 2 for RIGHT (Arrows)",
        "press_top": "Press 3 for TOP (IJKL)",
        "all_set": "ALL SET!",
        "dropping_puck": "Dropping puck in 4 seconds...",
        "grand_bash": "GRAND PADDLE BASH! -1 Point All Around",
        "ghost_tr": "Ghost Puck! Top & Right score.",
        "ghost_tl": "Ghost Puck! Top & Left score.",
        "ghost_lr": "Ghost Puck! Left & Right score.",
        "foul_lr": "FOUL: Left & Right Frozen!",
        "foul_lt": "FOUL: Left & Top Frozen!",
        "foul_rt": "FOUL: Right & Top Frozen!",
        "score_t": "Top scored!",
        "score_r": "Right scored!",
        "score_l": "Left scored!",
        "own_tr": "Own Goal! Top & Right score.",
        "own_tl": "Own Goal! Top & Left score.",
        "own_lr": "Own Goal! Left & Right score.",
        "tie_break": "TIE BREAK! FIRST TO {} WINS!",
        "match_over": "MATCH OVER! {} WINS!"
    },
    "hi": {
        "name": "2. हिन्दी (Hindi)",
        "setup_title": "ट्रॉकी 4K सेटअप",
        "select_lang": "भाषा चुनें:",
        "how_many": "कितने इंसान? (0, 1, 2, या 3 दबाएं)",
        "choose_side": "खिलाड़ी {} अपनी साइड चुनें:",
        "press_left": "LEFT के लिए 1 दबाएं (WASD)",
        "press_right": "RIGHT के लिए 2 दबाएं (Arrows)",
        "press_top": "TOP के लिए 3 दबाएं (IJKL)",
        "all_set": "सब तैयार!",
        "dropping_puck": "4 सेकंड में पक आ रहा है...",
        "grand_bash": "महा-टक्कर! सबका 1 पॉइंट कटा",
        "ghost_tr": "भूतिया पक! टॉप और राइट का स्कोर।",
        "ghost_tl": "भूतिया पक! टॉप और लेफ्ट का स्कोर।",
        "ghost_lr": "भूतिया पक! लेफ्ट और राइट का स्कोर।",
        "foul_lr": "फाउल: लेफ्ट और राइट फ्रीज!",
        "foul_lt": "फाउल: लेफ्ट और टॉप फ्रीज!",
        "foul_rt": "फाउल: राइट और टॉप फ्रीज!",
        "score_t": "टॉप का गोल!",
        "score_r": "राइट का गोल!",
        "score_l": "लेफ्ट का गोल!",
        "own_tr": "सेल्फ गोल! टॉप और राइट का स्कोर।",
        "own_tl": "सेल्फ गोल! टॉप और लेफ्ट का स्कोर।",
        "own_lr": "सेल्फ गोल! लेफ्ट और राइट का स्कोर।",
        "tie_break": "टाई ब्रेक! जो पहले {} बनाएगा वो जीतेगा!",
        "match_over": "मैच खत्म! {} की जीत!"
    },
    "mr": {
        "name": "3. मराठी (Marathi)",
        "setup_title": "TROCKEY 4K सेटअप",
        "select_lang": "भाषा निवडा:",
        "how_many": "किती माणसे? (0, 1, 2, किंवा 3 दाबा)",
        "choose_side": "खेळाडू {} बाजू निवडा:",
        "press_left": "LEFT साठी 1 दाबा (WASD)",
        "press_right": "RIGHT साठी 2 दाबा (Arrows)",
        "press_top": "TOP साठी 3 दाबा (IJKL)",
        "all_set": "सर्व तयार!",
        "dropping_puck": "4 सेकंदात पक पडत आहे...",
        "grand_bash": "महा-टक्कर! सर्वांचा 1 पॉईंट कमी",
        "ghost_tr": "गोस्ट पक! टॉप आणि राईटचा स्कोर.",
        "ghost_tl": "गोस्ट पक! टॉप आणि लेफ्टचा स्कोर.",
        "ghost_lr": "गोस्ट पक! लेफ्ट आणि राईटचा स्कोर.",
        "foul_lr": "फाऊल: लेफ्ट आणि राईट फ्रीझ!",
        "foul_lt": "फाऊल: लेफ्ट आणि टॉप फ्रीझ!",
        "foul_rt": "फाऊल: राईट आणि टॉप फ्रीझ!",
        "score_t": "टॉपचा गोल!",
        "score_r": "राईटचा गोल!",
        "score_l": "लेफ्टचा गोल!",
        "own_tr": "सेल्फ गोल! टॉप आणि राईटचा स्कोर.",
        "own_tl": "सेल्फ गोल! टॉप आणि लेफ्टचा स्कोर.",
        "own_lr": "सेल्फ गोल! लेफ्ट आणि राईटचा स्कोर.",
        "tie_break": "टाय ब्रेक! जो पहिले {} बनवेल तो जिंकेल!",
        "match_over": "सामना संपला! {} जिंकला/जिंकली!"
    },
    "es": {
        "name": "4. Español (Spanish)",
        "setup_title": "CONFIGURACIÓN TROCKEY 4K",
        "select_lang": "Seleccionar Idioma:",
        "how_many": "¿Cuántos humanos? (Pulsa 0, 1, 2, o 3)",
        "choose_side": "Jugador {} elige lado:",
        "press_left": "Pulsa 1 para IZQ. (WASD)",
        "press_right": "Pulsa 2 para DER. (Flechas)",
        "press_top": "Pulsa 3 para ARRIBA (IJKL)",
        "all_set": "¡TODO LISTO!",
        "dropping_puck": "Lanzando el disco en 4 segundos...",
        "grand_bash": "¡GRAN CHOQUE! -1 Punto para todos",
        "ghost_tr": "¡Disco Fantasma! Arriba y Derecha anotan.",
        "ghost_tl": "¡Disco Fantasma! Arriba e Izquierda anotan.",
        "ghost_lr": "¡Disco Fantasma! Izquierda y Derecha anotan.",
        "foul_lr": "FALTA: ¡Izquierda y Derecha congelados!",
        "foul_lt": "FALTA: ¡Izquierda y Arriba congelados!",
        "foul_rt": "FALTA: ¡Derecha y Arriba congelados!",
        "score_t": "¡Arriba anota!",
        "score_r": "¡Derecha anota!",
        "score_l": "¡Izquierda anota!",
        "own_tr": "¡Gol en contra! Arriba y Derecha anotan.",
        "own_tl": "¡Gol en contra! Arriba e Izquierda anotan.",
        "own_lr": "¡Gol en contra! Izquierda y Derecha anotan.",
        "tie_break": "¡DESEMPATE! ¡EL PRIMERO EN {} GANA!",
        "match_over": "¡FIN DEL JUEGO! ¡{} GANA!"
    },
    "fr": {
        "name": "5. Français (French)",
        "setup_title": "CONFIGURATION TROCKEY 4K",
        "select_lang": "Choisir la Langue:",
        "how_many": "Combien d'humains ? (0, 1, 2 ou 3)",
        "choose_side": "Joueur {} choisis ton côté:",
        "press_left": "Appuyez 1 pour GAUCHE (WASD)",
        "press_right": "Appuyez 2 pour DROITE (Flèches)",
        "press_top": "Appuyez 3 pour HAUT (IJKL)",
        "all_set": "C'EST PARTI !",
        "dropping_puck": "Lancement du palet dans 4s...",
        "grand_bash": "GRAND CHOC! -1 Point pour tous",
        "ghost_tr": "Palet Fantôme! Haut et Droite marquent.",
        "ghost_tl": "Palet Fantôme! Haut et Gauche marquent.",
        "ghost_lr": "Palet Fantôme! Gauche et Droite marquent.",
        "foul_lr": "FAUTE: Gauche et Droite gelés!",
        "foul_lt": "FAUTE: Gauche et Haut gelés!",
        "foul_rt": "FAUTE: Droite et Haut gelés!",
        "score_t": "Haut marque!",
        "score_r": "Droite marque!",
        "score_l": "Gauche marque!",
        "own_tr": "Contre son camp! Haut et Droite marquent.",
        "own_tl": "Contre son camp! Haut et Gauche marquent.",
        "own_lr": "Contre son camp! Gauche et Droite marquent.",
        "tie_break": "ÉGALITÉ ! LE PREMIER À {} GAGNE !",
        "match_over": "FIN DU MATCH ! {} GAGNE !"
    },
    "de": {
        "name": "6. Deutsch (German)",
        "setup_title": "TROCKEY 4K SETUP",
        "select_lang": "Sprache auswählen:",
        "how_many": "Wie viele Menschen? (0, 1, 2, 3)",
        "choose_side": "Spieler {} wähle die Seite:",
        "press_left": "Drücke 1 für LINKS (WASD)",
        "press_right": "Drücke 2 für RECHTS (Pfeile)",
        "press_top": "Drücke 3 für OBEN (IJKL)",
        "all_set": "ALLES KLAR!",
        "dropping_puck": "Puck fällt in 4 Sekunden...",
        "grand_bash": "MEGA-CRASH! -1 Punkt für alle",
        "ghost_tr": "Geister-Puck! Oben & Rechts punkten.",
        "ghost_tl": "Geister-Puck! Oben & Links punkten.",
        "ghost_lr": "Geister-Puck! Links & Rechts punkten.",
        "foul_lr": "FOUL: Links & Rechts eingefroren!",
        "foul_lt": "FOUL: Links & Oben eingefroren!",
        "foul_rt": "FOUL: Rechts & Oben eingefroren!",
        "score_t": "Oben punktet!",
        "score_r": "Rechts punktet!",
        "score_l": "Links punktet!",
        "own_tr": "Eigentor! Oben & Rechts punkten.",
        "own_tl": "Eigentor! Oben & Links punkten.",
        "own_lr": "Eigentor! Links & Rechts punkten.",
        "tie_break": "STECHEN! WER ZUERST {} HAT, GEWINNT!",
        "match_over": "SPIEL ENDE! {} GEWINNT!"
    },
    "nl": {
        "name": "7. Nederlands (Dutch)",
        "setup_title": "TROCKEY 4K INSTELLINGEN",
        "select_lang": "Selecteer Taal:",
        "how_many": "Hoeveel mensen? (0, 1, 2, of 3)",
        "choose_side": "Speler {} kies kant:",
        "press_left": "Druk 1 voor LINKS (WASD)",
        "press_right": "Druk 2 voor RECHTS (Pijltjes)",
        "press_top": "Druk 3 voor BOVEN (IJKL)",
        "all_set": "KLAAR!",
        "dropping_puck": "Puck valt in 4 seconden...",
        "grand_bash": "GROTE BOTSING! -1 Punt voor iedereen",
        "ghost_tr": "Spookpuck! Boven & Rechts scoren.",
        "ghost_tl": "Spookpuck! Boven & Links scoren.",
        "ghost_lr": "Spookpuck! Links & Rechts scoren.",
        "foul_lr": "OVERTREDING: Links & Rechts bevroren!",
        "foul_lt": "OVERTREDING: Links & Boven bevroren!",
        "foul_rt": "OVERTREDING: Rechts & Boven bevroren!",
        "score_t": "Boven scoort!",
        "score_r": "Rechts scoort!",
        "score_l": "Links scoort!",
        "own_tr": "Eigen doelpunt! Boven & Rechts scoren.",
        "own_tl": "Eigen doelpunt! Boven & Links scoren.",
        "own_lr": "Eigen doelpunt! Links & Rechts scoren.",
        "tie_break": "GELIJKSPEL! WIE HET EERST {} HEEFT WINT!",
        "match_over": "WEDSTRIJD VOORBIJ! {} WINT!"
    },
    "ja": {
        "name": "8. 日本語 (Japanese)",
        "setup_title": "TROCKEY 4K セットアップ",
        "select_lang": "言語を選択:",
        "how_many": "プレイヤーは何人？ (0, 1, 2, 3)",
        "choose_side": "プレイヤー {} 側を選択:",
        "press_left": "左 (WASD) は 1",
        "press_right": "右 (矢印キー) は 2",
        "press_top": "上 (IJKL) は 3",
        "all_set": "準備完了！",
        "dropping_puck": "4秒後にパックをドロップします...",
        "grand_bash": "大激突！ 全員 -1 ポイント",
        "ghost_tr": "ゴーストパック！ 上と右の得点。",
        "ghost_tl": "ゴーストパック！ 上と左の得点。",
        "ghost_lr": "ゴーストパック！ 左と右の得点。",
        "foul_lr": "ファウル：左と右がフリーズ！",
        "foul_lt": "ファウル：左と上がフリーズ！",
        "foul_rt": "ファウル：右と上がフリーズ！",
        "score_t": "上の得点！",
        "score_r": "右の得点！",
        "score_l": "左の得点！",
        "own_tr": "オウンゴール！ 上と右の得点。",
        "own_tl": "オウンゴール！ 上と左の得点。",
        "own_lr": "オウンゴール！ 左と右の得点。",
        "tie_break": "タイブレーク！ 先に {} 点取った方の勝ち！",
        "match_over": "ゲーム終了！ {} の勝ち！"
    },
    "ko": {
        "name": "9. 한국어 (Korean)",
        "setup_title": "TROCKEY 4K 설정",
        "select_lang": "언어 선택:",
        "how_many": "몇 명입니까? (0, 1, 2, 3 누름)",
        "choose_side": "플레이어 {} 진영 선택:",
        "press_left": "1: 왼쪽 (WASD)",
        "press_right": "2: 오른쪽 (방향키)",
        "press_top": "3: 위쪽 (IJKL)",
        "all_set": "준비 완료!",
        "dropping_puck": "4초 후 퍽이 떨어집니다...",
        "grand_bash": "대격돌! 모두 -1점",
        "ghost_tr": "유령 퍽! 위와 오른쪽 득점.",
        "ghost_tl": "유령 퍽! 위와 왼쪽 득점.",
        "ghost_lr": "유령 퍽! 왼쪽과 오른쪽 득점.",
        "foul_lr": "파울: 왼쪽 & 오른쪽 얼음!",
        "foul_lt": "파울: 왼쪽 & 위쪽 얼음!",
        "foul_rt": "파울: 오른쪽 & 위쪽 얼음!",
        "score_t": "위쪽 득점!",
        "score_r": "오른쪽 득점!",
        "score_l": "왼쪽 득점!",
        "own_tr": "자책골! 위와 오른쪽 득점.",
        "own_tl": "자책골! 위와 왼쪽 득점.",
        "own_lr": "자책골! 왼쪽과 오른쪽 득점.",
        "tie_break": "타이브레이크! {}점 선취 승리!",
        "match_over": "게임 종료! {} 승리!"
    },
    "zh": {
        "name": "1. 简体中文 (Chinese)",
        "setup_title": "TROCKEY 4K 设置",
        "select_lang": "选择语言:",
        "how_many": "几名玩家？ (按 0, 1, 2, 或 3)",
        "choose_side": "玩家 {} 选择方向:",
        "press_left": "按 1 选择左侧 (WASD)",
        "press_right": "按 2 选择右侧 (方向键)",
        "press_top": "按 3 选择上方 (IJKL)",
        "all_set": "准备就绪！",
        "dropping_puck": "4秒后发球...",
        "grand_bash": "大碰撞！全体 -1 分",
        "ghost_tr": "幽灵球！上和右得分。",
        "ghost_tl": "幽灵球！上和左得分。",
        "ghost_lr": "幽灵球！左和右得分。",
        "foul_lr": "犯规：左和右冻结！",
        "foul_lt": "犯规：左和上冻结！",
        "foul_rt": "犯规：右和上冻结！",
        "score_t": "上方得分！",
        "score_r": "右侧得分！",
        "score_l": "左侧得分！",
        "own_tr": "乌龙球！上和右得分。",
        "own_tl": "乌龙球！上和左得分。",
        "own_lr": "乌龙球！左和右得分。",
        "tie_break": "加时赛！先得 {} 分者胜！",
        "match_over": "比赛结束！{} 获胜！"
    },
    "th": {
        "name": "2. ไทย (Thai)",
        "setup_title": "ตั้งค่า TROCKEY 4K",
        "select_lang": "เลือกภาษา:",
        "how_many": "จำนวนผู้เล่น? (กด 0, 1, 2, 3)",
        "choose_side": "ผู้เล่น {} เลือกฝั่ง:",
        "press_left": "กด 1 ซ้าย (WASD)",
        "press_right": "กด 2 ขวา (ลูกศร)",
        "press_top": "กด 3 บน (IJKL)",
        "all_set": "พร้อม!",
        "dropping_puck": "เริ่มเกมใน 4 วินาที...",
        "grand_bash": "ชนสนั่น! หัก 1 คะแนนทุกคน",
        "ghost_tr": "ลูกผีผลัก! บนและขวาได้คะแนน",
        "ghost_tl": "ลูกผีผลัก! บนและซ้ายได้คะแนน",
        "ghost_lr": "ลูกผีผลัก! ซ้ายและขวาได้คะแนน",
        "foul_lr": "ฟาวล์: ซ้ายและขวาถูกแช่แข็ง!",
        "foul_lt": "ฟาวล์: ซ้ายและบนถูกแช่แข็ง!",
        "foul_rt": "ฟาวล์: ขวาและบนถูกแช่แข็ง!",
        "score_t": "บนได้คะแนน!",
        "score_r": "ขวาได้คะแนน!",
        "score_l": "ซ้ายได้คะแนน!",
        "own_tr": "ทำเข้าประตูตัวเอง! บนและขวาได้คะแนน",
        "own_tl": "ทำเข้าประตูตัวเอง! บนและซ้ายได้คะแนน",
        "own_lr": "ทำเข้าประตูตัวเอง! ซ้ายและขวาได้คะแนน",
        "tie_break": "ไทเบรก! ใครถึง {} ก่อนชนะ!",
        "match_over": "จบเกม! {} ชนะ!"
    },
    "id": {
        "name": "3. Bahasa Indonesia",
        "setup_title": "PENGATURAN TROCKEY 4K",
        "select_lang": "Pilih Bahasa:",
        "how_many": "Berapa pemain? (Tekan 0, 1, 2, 3)",
        "choose_side": "Pemain {} pilih sisi:",
        "press_left": "Tekan 1 untuk KIRI (WASD)",
        "press_right": "Tekan 2 untuk KANAN (Panah)",
        "press_top": "Tekan 3 untuk ATAS (IJKL)",
        "all_set": "SIAP!",
        "dropping_puck": "Puck meluncur dalam 4 detik...",
        "grand_bash": "TABRAKAN BESAR! -1 Poin Semua",
        "ghost_tr": "Puck Hantu! Atas & Kanan mencetak poin.",
        "ghost_tl": "Puck Hantu! Atas & Kiri mencetak poin.",
        "ghost_lr": "Puck Hantu! Kiri & Kanan mencetak poin.",
        "foul_lr": "PELANGGARAN: Kiri & Kanan Beku!",
        "foul_lt": "PELANGGARAN: Kiri & Atas Beku!",
        "foul_rt": "PELANGGARAN: Kanan & Atas Beku!",
        "score_t": "Atas mencetak poin!",
        "score_r": "Kanan mencetak poin!",
        "score_l": "Kiri mencetak poin!",
        "own_tr": "Gol Bunuh Diri! Atas & Kanan mencetak poin.",
        "own_tl": "Gol Bunuh Diri! Atas & Kiri mencetak poin.",
        "own_lr": "Gol Bunuh Diri! Kiri & Kanan mencetak poin.",
        "tie_break": "SERI! YANG PERTAMA MENCAPAI {} MENANG!",
        "match_over": "PERMAINAN SELESAI! {} MENANG!"
    },
    "ta": {
        "name": "4. தமிழ் (Tamil)",
        "setup_title": "TROCKEY 4K அமைப்பு",
        "select_lang": "மொழியைத் தேர்ந்தெடு:",
        "how_many": "எத்தனை வீரர்கள்? (0, 1, 2, 3)",
        "choose_side": "வீரர் {} திசையைத் தேர்ந்தெடு:",
        "press_left": "இடது (WASD) - 1",
        "press_right": "வலது (Arrows) - 2",
        "press_top": "மேல் (IJKL) - 3",
        "all_set": "தயார்!",
        "dropping_puck": "4 வினாடிகளில் பக் விழும்...",
        "grand_bash": "மாபெரும் மோதல்! அனைவருக்கும் -1",
        "ghost_tr": "பேய் பக்! மேல் & வலது புள்ளி.",
        "ghost_tl": "பேய் பக்! மேல் & இடது புள்ளி.",
        "ghost_lr": "பேய் பக்! இடது & வலது புள்ளி.",
        "foul_lr": "ஃபவுல்: இடது & வலது ஃப்ரீஸ்!",
        "foul_lt": "ஃபவுல்: இடது & மேல் ஃப்ரீஸ்!",
        "foul_rt": "ஃபவுல்: வலது & மேல் ஃப்ரீஸ்!",
        "score_t": "மேல் புள்ளி!",
        "score_r": "வலது புள்ளி!",
        "score_l": "இடது புள்ளி!",
        "own_tr": "சுய கோல்! மேல் & வலது புள்ளி.",
        "own_tl": "சுய கோல்! மேல் & இடது புள்ளி.",
        "own_lr": "சுய கோல்! இடது & வலது புள்ளி.",
        "tie_break": "டை பிரேக்! முதலில் {} எடுப்பவர் வெற்றி!",
        "match_over": "ஆட்டம் முடிந்தது! {} வெற்றி!"
    },
    "te": {
        "name": "5. తెలుగు (Telugu)",
        "setup_title": "TROCKEY 4K సెటప్",
        "select_lang": "భాషను ఎంచుకోండి:",
        "how_many": "ఎంతమంది? (0, 1, 2, 3 నొక్కండి)",
        "choose_side": "ఆటగాడు {} వైపు ఎంచుకోండి:",
        "press_left": "ఎడమ (WASD) కోసం 1 నొక్కండి",
        "press_right": "కుడి (Arrows) కోసం 2 నొక్కండి",
        "press_top": "పైన (IJKL) కోసం 3 నొక్కండి",
        "all_set": "సిద్ధం!",
        "dropping_puck": "4 సెకన్లలో పక్ వస్తోంది...",
        "grand_bash": "మహా ఢీ! అందరికీ -1 పాయింట్",
        "ghost_tr": "దెయ్యం పక్! పైన & కుడికి పాయింట్.",
        "ghost_tl": "దెయ్యం పక్! పైన & ఎడమకు పాయింట్.",
        "ghost_lr": "దెయ్యం పక్! ఎడమ & కుడికి పాయింట్.",
        "foul_lr": "ఫౌల్: ఎడమ & కుడి ఫ్రీజ్!",
        "foul_lt": "ఫౌల్: ఎడమ & పైన ఫ్రీజ్!",
        "foul_rt": "ఫౌల్: కుడి & పైన ఫ్రీజ్!",
        "score_t": "పైన పాయింట్!",
        "score_r": "కుడి పాయింట్!",
        "score_l": "ఎడమ పాయింట్!",
        "own_tr": "సెల్ఫ్ గోల్! పైన & కుడికి పాయింట్.",
        "own_tl": "సెల్ఫ్ గోల్! పైన & ఎడమకు పాయింట్.",
        "own_lr": "సెల్ఫ్ గోల్! ఎడమ & కుడికి పాయింట్.",
        "tie_break": "టై బ్రేక్! మొదట {} సాధించిన వారు విజేత!",
        "match_over": "ఆట ముగిసింది! {} విజేత!"
    },
    "ml": {
        "name": "6. മലയാളം (Malayalam)",
        "setup_title": "TROCKEY 4K സജ്ജീകരണം",
        "select_lang": "ഭാഷ തിരഞ്ഞെടുക്കുക:",
        "how_many": "എത്ര കളിക്കാർ? (0, 1, 2, 3)",
        "choose_side": "കളിക്കാരൻ {} വശം തിരഞ്ഞെടുക്കുക:",
        "press_left": "ഇടതിന് 1 (WASD)",
        "press_right": "വലതിന് 2 (Arrows)",
        "press_top": "മുകളിലേക്ക് 3 (IJKL)",
        "all_set": "തയ്യാറാണ്!",
        "dropping_puck": "4 സെക്കൻഡിൽ പക്ക് വരുന്നു...",
        "grand_bash": "മഹാ കൂട്ടിയിടി! എല്ലാവർക്കും -1",
        "ghost_tr": "ഗോസ്റ്റ് പക്ക്! മുകൾ & വലത് പോയിന്റ്.",
        "ghost_tl": "ഗോസ്റ്റ് പക്ക്! മുകൾ & ഇടത് പോയിന്റ്.",
        "ghost_lr": "ഗോസ്റ്റ് പക്ക്! ഇടത് & വലത് പോയിന്റ്.",
        "foul_lr": "ഫൗൾ: ഇടത് & വലത് ഫ്രീസ്!",
        "foul_lt": "ഫൗൾ: ഇടത് & മുകൾ ഫ്രീസ്!",
        "foul_rt": "ഫൗൾ: വലത് & മുകൾ ഫ്രീസ്!",
        "score_t": "മുകൾ പോയിന്റ്!",
        "score_r": "വലത് പോയിന്റ്!",
        "score_l": "ഇടത് പോയിന്റ്!",
        "own_tr": "സെൽഫ് ഗോൾ! മുകൾ & വലത് പോയിന്റ്.",
        "own_tl": "സെൽഫ് ഗോൾ! മുകൾ & ഇടത് പോയിന്റ്.",
        "own_lr": "സെൽഫ് ഗോൾ! ഇടത് & വലത് പോയിന്റ്.",
        "tie_break": "ടൈ ബ്രേക്ക്! ആദ്യം {} നേടുന്നവർ വിജയി!",
        "match_over": "ഗെയിം കഴിഞ്ഞു! {} വിജയിച്ചു!"
    },
    "ru": {
        "name": "7. Русский (Russian)",
        "setup_title": "НАСТРОЙКА TROCKEY 4K",
        "select_lang": "Выберите язык:",
        "how_many": "Сколько людей? (Нажмите 0, 1, 2, 3)",
        "choose_side": "Игрок {} выберите сторону:",
        "press_left": "1 для ЛЕВО (WASD)",
        "press_right": "2 для ПРАВО (Стрелки)",
        "press_top": "3 для ВЕРХ (IJKL)",
        "all_set": "ГOТОВО!",
        "dropping_puck": "Шайба появится через 4 сек...",
        "grand_bash": "БОЛЬШОЕ СТОЛКНОВЕНИЕ! Всем -1",
        "ghost_tr": "Призрачная шайба! Верх и Право получают очко.",
        "ghost_tl": "Призрачная шайба! Верх и Лево получают очко.",
        "ghost_lr": "Призрачная шайба! Лево и Право получают очко.",
        "foul_lr": "ФОЛ: Лево и Право заморожены!",
        "foul_lt": "ФОЛ: Лево и Верх заморожены!",
        "foul_rt": "ФОЛ: Право и Верх заморожены!",
        "score_t": "Верх забивает!",
        "score_r": "Право забивает!",
        "score_l": "Лево забивает!",
        "own_tr": "Автогол! Верх и Право получают очко.",
        "own_tl": "Автогол! Верх и Лево получают очко.",
        "own_lr": "Автогол! Лево и Право получают очко.",
        "tie_break": "ТАЙ-БРЕЙК! ДО {} ПОБЕД!",
        "match_over": "ИГРА ОКОНЧЕНА! {} ПОБЕЖДАЕТ!"
    },
    "gu": {
        "name": "8. ગુજરાતી (Gujarati)",
        "setup_title": "TROCKEY 4K સેટઅપ",
        "select_lang": "ભાષા પસંદ કરો:",
        "how_many": "કેટલા ખેલાડીઓ? (0, 1, 2, 3 દબાવો)",
        "choose_side": "ખેલાડી {} બાજુ પસંદ કરો:",
        "press_left": "ડાબી (WASD) માટે 1 દબાવો",
        "press_right": "જમણી (Arrows) માટે 2 દબાવો",
        "press_top": "ઉપર (IJKL) માટે 3 દબાવો",
        "all_set": "બધું તૈયાર!",
        "dropping_puck": "4 સેકન્ડમાં પક આવી રહ્યો છે...",
        "grand_bash": "મહા-ટક્કર! બધાના 1 પોઈન્ટ કટ",
        "ghost_tr": "ભૂતિયા પક! ઉપર અને જમણીનો સ્કોર.",
        "ghost_tl": "ભૂતિયા પક! ઉપર અને ડાબીનો સ્કોર.",
        "ghost_lr": "ભૂતિયા પક! ડાબી અને જમણીનો સ્કોર.",
        "foul_lr": "ફાઉલ: ડાબી અને જમણી ફ્રીઝ!",
        "foul_lt": "ફાઉલ: ડાબી અને ઉપર ફ્રીઝ!",
        "foul_rt": "ફાઉલ: જમણી અને ઉપર ફ્રીઝ!",
        "score_t": "ઉપરનો સ્કોર!",
        "score_r": "જમણીનો સ્કોર!",
        "score_l": "ડાબીનો સ્કોર!",
        "own_tr": "સેલ્ફ ગોલ! ઉપર અને જમણીનો સ્કોર.",
        "own_tl": "સેલ્ફ ગોલ! ઉપર અને ડાબીનો સ્કોર.",
        "own_lr": "સેલ્ફ ગોલ! ડાબી અને જમણીનો સ્કોર.",
        "tie_break": "ટાઈ બ્રેક! પહેલા {} સ્કોર કરનાર વિજેતા!",
        "match_over": "મેચ પૂરી! {} ની જીત!"
    },
    "fi": {
        "name": "9. Suomi (Finnish)",
        "setup_title": "TROCKEY 4K ASETUKSET",
        "select_lang": "Valitse Kieli:",
        "how_many": "Kuinka monta ihmistä? (0, 1, 2, 3)",
        "choose_side": "Pelaaja {} valitse puoli:",
        "press_left": "Paina 1: VASEMMALLE (WASD)",
        "press_right": "Paina 2: OIKEALLE (Nuolet)",
        "press_top": "Paina 3: YLÖS (IJKL)",
        "all_set": "VALMISTA!",
        "dropping_puck": "Kiekko putoaa 4 sekunnissa...",
        "grand_bash": "SUURI TÖRMÄYS! -1 Piste Kaikille",
        "ghost_tr": "Haamukiekko! Ylös & Oikea saavat pisteen.",
        "ghost_tl": "Haamukiekko! Ylös & Vasen saavat pisteen.",
        "ghost_lr": "Haamukiekko! Vasen & Oikea saavat pisteen.",
        "foul_lr": "VIRHE: Vasen & Oikea jäätyvät!",
        "foul_lt": "VIRHE: Vasen & Ylös jäätyvät!",
        "foul_rt": "VIRHE: Oikea & Ylös jäätyvät!",
        "score_t": "Ylös teki maalin!",
        "score_r": "Oikea teki maalin!",
        "score_l": "Vasen teki maalin!",
        "own_tr": "Oma maali! Ylös & Oikea saavat pisteen.",
        "own_tl": "Oma maali! Ylös & Vasen saavat pisteen.",
        "own_lr": "Oma maali! Vasen & Oikea saavat pisteen.",
        "tie_break": "TASAPELI! ENSIMMÄINEN {} VOITTAA!",
        "match_over": "PELI OHI! {} VOITTAA!"
    }
}