STRINGS = {
    "en": {
        "name": "English",
        "setup_title": "TROCKEY 4K SETUP",
        "select_lang": "Select Language:",
        "how_many": "How many humans? (Press 0, 1, 2, or 3)",
        "choose_side": "Player {} choose side:",
        "press_left": "Press 1 for LEFT (WASD)",
        "press_right": "Press 2 for RIGHT (Arrows)",
        "press_top": "Press 3 for TOP (IJKL)",
        "all_set": "ALL SET!",
        "dropping_puck": "Dropping puck in 4 seconds...",
        "grand_bash": "GRAND PADDLE BASH! -1 Point All Around",
        "ghost_tr": "Ghost Puck! Top & Right score.",
        "ghost_tl": "Ghost Puck! Top & Left score.",
        "ghost_lr": "Ghost Puck! Left & Right score.",
        "foul_lr": "FOUL: Left & Right Frozen!",
        "foul_lt": "FOUL: Left & Top Frozen!",
        "foul_rt": "FOUL: Right & Top Frozen!",
        "score_t": "Top scored!",
        "score_r": "Right scored!",
        "score_l": "Left scored!",
        "own_tr": "Own Goal! Top & Right score.",
        "own_tl": "Own Goal! Top & Left score.",
        "own_lr": "Own Goal! Left & Right score.",
        "tie_break": "TIE BREAK! FIRST TO {} WINS!",
        "match_over": "MATCH OVER! {} WINS!"
    },
    "hi": {
        "name": "हिन्दी",
        "setup_title": "ट्रॉकी 4K सेटअप",
        "select_lang": "भाषा चुनें:",
        "how_many": "कितने इंसान? (0, 1, 2, या 3 दबाएं)",
        "choose_side": "खिलाड़ी {} अपनी साइड चुनें:",
        "press_left": "LEFT के लिए 1 दबाएं (WASD)",
        "press_right": "RIGHT के लिए 2 दबाएं (Arrows)",
        "press_top": "TOP के लिए 3 दबाएं (IJKL)",
        "all_set": "सब तैयार!",
        "dropping_puck": "4 सेकंड में पक आ रहा है...",
        "grand_bash": "महा-टक्कर! सबका 1 पॉइंट कटा",
        "ghost_tr": "भूतिया पक! टॉप और राइट का स्कोर।",
        "ghost_tl": "भूतिया पक! टॉप और लेफ्ट का स्कोर।",
        "ghost_lr": "भूतिया पक! लेफ्ट और राइट का स्कोर।",
        "foul_lr": "फाउल: लेफ्ट और राइट फ्रीज!",
        "foul_lt": "फाउल: लेफ्ट और टॉप फ्रीज!",
        "foul_rt": "फाउल: राइट और टॉप फ्रीज!",
        "score_t": "टॉप का गोल!",
        "score_r": "राइट का गोल!",
        "score_l": "लेफ्ट का गोल!",
        "own_tr": "सेल्फ गोल! टॉप और राइट का स्कोर।",
        "own_tl": "सेल्फ गोल! टॉप और लेफ्ट का स्कोर।",
        "own_lr": "सेल्फ गोल! लेफ्ट और राइट का स्कोर।",
        "tie_break": "टाई ब्रेक! जो पहले {} बनाएगा वो जीतेगा!",
        "match_over": "मैच खत्म! {} की जीत!"
    },
    "es": {
        "name": "Español",
        "setup_title": "CONFIGURACIÓN TROCKEY 4K",
        "select_lang": "Seleccionar Idioma:",
        "how_many": "¿Cuántos humanos? (Pulsa 0, 1, 2, o 3)",
        "choose_side": "Jugador {} elige lado:",
        "press_left": "Pulsa 1 para IZQUIERDA (WASD)",
        "press_right": "Pulsa 2 para DERECHA (Flechas)",
        "press_top": "Pulsa 3 para ARRIBA (IJKL)",
        "all_set": "¡TODO LISTO!",
        "dropping_puck": "Lanzando el disco en 4 segundos...",
        "grand_bash": "¡GRAN CHOQUE! -1 Punto para todos",
        "ghost_tr": "¡Disco Fantasma! Arriba y Derecha anotan.",
        "ghost_tl": "¡Disco Fantasma! Arriba e Izquierda anotan.",
        "ghost_lr": "¡Disco Fantasma! Izquierda y Derecha anotan.",
        "foul_lr": "FALTA: ¡Izquierda y Derecha congelados!",
        "foul_lt": "FALTA: ¡Izquierda y Arriba congelados!",
        "foul_rt": "FALTA: ¡Derecha y Arriba congelados!",
        "score_t": "¡Arriba anota!",
        "score_r": "¡Derecha anota!",
        "score_l": "¡Izquierda anota!",
        "own_tr": "¡Gol en contra! Arriba y Derecha anotan.",
        "own_tl": "¡Gol en contra! Arriba e Izquierda anotan.",
        "own_lr": "¡Gol en contra! Izquierda y Derecha anotan.",
        "tie_break": "¡DESEMPATE! ¡EL PRIMERO EN {} GANA!",
        "match_over": "¡FIN DEL JUEGO! ¡{} GANA!"
    },
    "fr": {
        "name": "Français",
        "setup_title": "CONFIGURATION TROCKEY 4K",
        "select_lang": "Choisir la Langue:",
        "how_many": "Combien d'humains ? (Appuyez sur 0, 1, 2 ou 3)",
        "choose_side": "Joueur {} choisis ton côté:",
        "press_left": "Appuyez sur 1 pour GAUCHE (WASD)",
        "press_right": "Appuyez sur 2 pour DROITE (Flèches)",
        "press_top": "Appuyez sur 3 pour HAUT (IJKL)",
        "all_set": "C'EST PARTI !",
        "dropping_puck": "Lancement du palet dans 4 secondes...",
        "grand_bash": "GRAND CHOC! -1 Point pour tous",
        "ghost_tr": "Palet Fantôme! Haut et Droite marquent.",
        "ghost_tl": "Palet Fantôme! Haut et Gauche marquent.",
        "ghost_lr": "Palet Fantôme! Gauche et Droite marquent.",
        "foul_lr": "FAUTE: Gauche et Droite gelés!",
        "foul_lt": "FAUTE: Gauche et Haut gelés!",
        "foul_rt": "FAUTE: Droite et Haut gelés!",
        "score_t": "Haut marque!",
        "score_r": "Droite marque!",
        "score_l": "Gauche marque!",
        "own_tr": "Contre son camp! Haut et Droite marquent.",
        "own_tl": "Contre son camp! Haut et Gauche marquent.",
        "own_lr": "Contre son camp! Gauche et Droite marquent.",
        "tie_break": "ÉGALITÉ ! LE PREMIER À {} GAGNE !",
        "match_over": "FIN DU MATCH ! {} GAGNE !"
    },
    "de": {
        "name": "Deutsch",
        "setup_title": "TROCKEY 4K SETUP",
        "select_lang": "Sprache auswählen:",
        "how_many": "Wie viele Menschen? (0, 1, 2, oder 3 drücken)",
        "choose_side": "Spieler {} wähle die Seite:",
        "press_left": "Drücke 1 für LINKS (WASD)",
        "press_right": "Drücke 2 für RECHTS (Pfeiltasten)",
        "press_top": "Drücke 3 für OBEN (IJKL)",
        "all_set": "ALLES KLAR!",
        "dropping_puck": "Puck fällt in 4 Sekunden...",
        "grand_bash": "MEGA-CRASH! -1 Punkt für alle",
        "ghost_tr": "Geister-Puck! Oben & Rechts punkten.",
        "ghost_tl": "Geister-Puck! Oben & Links punkten.",
        "ghost_lr": "Geister-Puck! Links & Rechts punkten.",
        "foul_lr": "FOUL: Links & Rechts eingefroren!",
        "foul_lt": "FOUL: Links & Oben eingefroren!",
        "foul_rt": "FOUL: Rechts & Oben eingefroren!",
        "score_t": "Oben punktet!",
        "score_r": "Rechts punktet!",
        "score_l": "Links punktet!",
        "own_tr": "Eigentor! Oben & Rechts punkten.",
        "own_tl": "Eigentor! Oben & Links punkten.",
        "own_lr": "Eigentor! Links & Rechts punkten.",
        "tie_break": "STECHEN! WER ZUERST {} HAT, GEWINNT!",
        "match_over": "SPIEL ENDE! {} GEWINNT!"
    },
    "nl": {
        "name": "Nederlands",
        "setup_title": "TROCKEY 4K INSTELLINGEN",
        "select_lang": "Selecteer Taal:",
        "how_many": "Hoeveel mensen? (Druk 0, 1, 2, of 3)",
        "choose_side": "Speler {} kies kant:",
        "press_left": "Druk 1 voor LINKS (WASD)",
        "press_right": "Druk 2 voor RECHTS (Pijltjes)",
        "press_top": "Druk 3 voor BOVEN (IJKL)",
        "all_set": "KLAAR!",
        "dropping_puck": "Puck valt in 4 seconden...",
        "grand_bash": "GROTE BOTSING! -1 Punt voor iedereen",
        "ghost_tr": "Spookpuck! Boven & Rechts scoren.",
        "ghost_tl": "Spookpuck! Boven & Links scoren.",
        "ghost_lr": "Spookpuck! Links & Rechts scoren.",
        "foul_lr": "OVERTREDING: Links & Rechts bevroren!",
        "foul_lt": "OVERTREDING: Links & Boven bevroren!",
        "foul_rt": "OVERTREDING: Rechts & Boven bevroren!",
        "score_t": "Boven scoort!",
        "score_r": "Rechts scoort!",
        "score_l": "Links scoort!",
        "own_tr": "Eigen doelpunt! Boven & Rechts scoren.",
        "own_tl": "Eigen doelpunt! Boven & Links scoren.",
        "own_lr": "Eigen doelpunt! Links & Rechts scoren.",
        "tie_break": "GELIJKSPEL! WIE HET EERST {} HEEFT WINT!",
        "match_over": "WEDSTRIJD VOORBIJ! {} WINT!"
    },
    "ja": {
        "name": "日本語",
        "setup_title": "TROCKEY 4K セットアップ",
        "select_lang": "言語を選択:",
        "how_many": "プレイヤーは何人ですか？ (0, 1, 2, 3 を押す)",
        "choose_side": "プレイヤー {} 側を選択:",
        "press_left": "左 (WASD) は 1 を押す",
        "press_right": "右 (矢印キー) は 2 を押す",
        "press_top": "上 (IJKL) は 3 を押す",
        "all_set": "準備完了！",
        "dropping_puck": "4秒後にパックをドロップします...",
        "grand_bash": "大激突！ 全員 -1 ポイント",
        "ghost_tr": "ゴーストパック！ 上と右の得点。",
        "ghost_tl": "ゴーストパック！ 上と左の得点。",
        "ghost_lr": "ゴーストパック！ 左と右の得点。",
        "foul_lr": "ファウル：左と右がフリーズ！",
        "foul_lt": "ファウル：左と上がフリーズ！",
        "foul_rt": "ファウル：右と上がフリーズ！",
        "score_t": "上の得点！",
        "score_r": "右の得点！",
        "score_l": "左の得点！",
        "own_tr": "オウンゴール！ 上と右の得点。",
        "own_tl": "オウンゴール！ 上と左の得点。",
        "own_lr": "オウンゴール！ 左と右の得点。",
        "tie_break": "タイブレーク！ 先に {} 点取った方の勝ち！",
        "match_over": "ゲーム終了！ {} の勝ち！"
    }
}